### ISSUE TITLE
MetaData and README version mismatch

### ISSUE THREAD

**Issue by lennartkoopmann** [underdogio/graylog-plugin-datadog#1]
Thanks for writing this! Great stuff. :)

The README says that it requires at least Graylog v2.0 but the MetaData requires v1.2. I guess you used the latest (v2.0-x) plugin archetype and did not update the README.

**Comment by brettlangdon** [comment]
Good catch, thanks!

Yeah, that is basically what happened.

I also had issues getting the Travis release build to work, missing GitHub
credentials or something.

**Comment by brettlangdon** [comment]
@lennartkoopmann does this also have to be updated in `pom.xml`? /me hasn't done much Java programming lately

https://github.com/underdogio/graylog-plugin-datadog/blob/3916382e49ec0fc76c160101f2e7c40678f2dff3/pom.xml#L35

**Comment by lennartkoopmann** [comment]
Yes, set it to use `1.3.4`. :)

**Comment by brettlangdon** [comment]
alright, should be all updated and ready now. thanks for the help :)
